# Generated by Django 4.2.11 on 2026-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_savingsgoal_savingscontribution_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
