# Generated by Django 4.2.11 on 2026-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0003_category_monthly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="theme",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
