# Generated by Django 4.2.11 on 2026-05-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_import", "0001_initial"),
        ("budgets", "0005_incomesalarychange_categorytheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="import_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="pdf_import.pdfimportsession",
            ),
        ),
    ]
